name: CI Pipeline

on:
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-venv
        
    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate

        # Install testing and linting dependencies
        pip install pytest httpx  # for unit tests
        pip install black  # for code formatting
        pip install bandit  # for security analysis
        pip install pip-audit  # for dependency vulnerabilities
        pip install detect-secrets  # for secrets scanning
        
    - name: Run tests
      run: |
        source venv/bin/activate
        chmod +x run_tests.sh
        ./run_tests.sh
        
    - name: Build and verify
      run: |
        source venv/bin/activate
        chmod +x build.sh
        ./build.sh 